name: afdyl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.7.2
dependencies:
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated from 5.0.0
  firebase_auth: ^5.3.1 # Updated from 5.3.1
  cloud_firestore: ^5.4.4 # Updated from 5.4.4
  get: ^4.6.6
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic