name: afdyl
description: "Al-Qur’an for Dyslexia."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Supabase services
  supabase_flutter: ^2.6.0
  # Environment variables
  flutter_dotenv: ^5.1.0

  # Deep linking for password reset
  app_links: ^6.3.2
  
  # State management (pakai GetX untuk route & controller)
  get: ^4.6.6
  
  # Fonts
  google_fonts: ^6.1.0

  # Lokasi & arah
  geolocator: ^12.0.0      # ambil posisi GPS
  geocoding: ^2.1.0        # konversi koordinat ↔ alamat
  flutter_compass: ^0.8.0  # sensor kompas (arah kiblat)
  permission_handler: ^11.3.1  # izin akses lokasi, storage, dll.

  # HTTP & UI tambahan
  http: ^1.1.0             # request API
  fluttertoast: ^8.2.8     # pesan popup
  flutter_tts: ^3.8.5      # text-to-speech (bunyi huruf, instruksi)
  image_picker: ^1.1.2     # ambil gambar dari kamera/galeri
  audioplayers: ^6.5.1     # mainkan audio (huruf hijaiyah, instruksi)
  flutter_lints: ^5.0.0    # aturan linting (best practice)
  cupertino_icons: ^1.0.2  # ikon gaya iOS
  speech_to_text: ^7.3.0   # konversi suara → teks (latihan pengucapan)
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5    # akses direktori temporary untuk share
  share_plus: ^10.1.3      # share ke social media (Instagram, WhatsApp, dll)

  # SVG processing untuk tracing system
  flutter_svg: ^2.0.9
  path_drawing: ^1.0.1
  xml: ^6.4.2

  # Machine Learning (temporarily disabled for web compatibility)
  # tflite_flutter: ^0.10.4
  # tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGO AFDYL.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/LOGO AFDYL.png"
  remove_alpha_ios: true  # Remove alpha channel untuk Apple App Store

flutter:
  uses-material-design: true

  # Asset yang dipakai dalam aplikasi
  assets:
    - .env
    - assets/images/LOGO AFDYL.png
    - assets/images/Kaaba.png
    - assets/images/muslimah_hijab.png
    - assets/images/ic_checkmark.png
    - assets/images/ic_quran.png
    - assets/images/ic_hijaiyah.png
    - assets/images/ic_sound_wave.png
    - assets/images/img_masjid.png
    - assets/images/ic_point.png
    - assets/images/ic_rank.png
    - assets/images/ic_shuffle.png
    - assets/images/ic_tuning.png
    - assets/images/ic_playbutton.png
    - assets/images/bg_wrapped.png
    - assets/images/bg_wrapped_2.png
    - assets/images/pressed.png
    - assets/images/finish.png
    - assets/images/Star 2.png
    - assets/images/Star 3.png
    
    # Hijaiyah Dashed SVG untuk tracing
    - assets/images/hijaiyah_svg_dashed/
    
    # Hijaiyah Original PNG untuk background
    - assets/images/hijaiyah_original/
      
    # Audio huruf hijaiyah
    - assets/audio/ain.m4a
    - assets/audio/alif.m4a
    - assets/audio/ba.m4a
    - assets/audio/dal.m4a
    - assets/audio/dhad.m4a
    - assets/audio/dzal.m4a
    - assets/audio/fa.m4a
    - assets/audio/ghain.m4a
    - assets/audio/ha.m4a    # ha kecil
    - assets/audio/HHa.m4a   # ha besar
    - assets/audio/jim.m4a
    - assets/audio/kaf.m4a
    - assets/audio/kha.m4a
    - assets/audio/lam.m4a
    - assets/audio/mim.m4a
    - assets/audio/nun.m4a
    - assets/audio/qaf.m4a
    - assets/audio/ra.m4a
    - assets/audio/shad.m4a
    - assets/audio/sin.m4a
    - assets/audio/syin.m4a
    - assets/audio/ta.m4a
    - assets/audio/tha.m4a
    - assets/audio/tsa.m4a
    - assets/audio/waw.m4a
    - assets/audio/ya.m4a
    - assets/audio/zai.m4a
    - assets/audio/zha.m4a
  # Audio benar salah
    - assets/audio/salah.m4a
    - assets/audio/benar.m4a

  # Font custom yang digunakan di aplikasi
  fonts:
    - family: OpenDyslexic   # font ramah disleksia
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic
    - family: Amiri   # font Arab klasik untuk Al-Qur’an
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Maqroo
      fonts:
        - asset: assets/fonts/Maqroo-Regular.ttf
