name: afdyl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Supabase services
  supabase_flutter: ^2.6.0
  # Environment variables
  flutter_dotenv: ^5.1.0

  # State management
  get: ^4.6.6
  
  # Fonts
  google_fonts: ^6.1.0

  # Lokasi & arah
  geolocator: ^12.0.0      # ambil posisi GPS
  geocoding: ^2.1.0        # konversi koordinat ↔ alamat
  flutter_compass: ^0.8.0  # sensor kompas (arah kiblat)
  permission_handler: ^11.3.1  # izin akses lokasi, storage, dll.

  # Lainnya
  http: ^1.1.0             # request API
  fluttertoast: ^8.2.8     # pesan popup
  flutter_tts: ^3.8.5      # text-to-speech (bunyi huruf, instruksi)
  image_picker: ^1.1.2
  audioplayers: ^6.5.1
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.3.0

  # Machine Learning (temporarily disabled for web compatibility)
  # tflite_flutter: ^0.10.4


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/Kaaba.png
    - assets/images/muslimah_hijab.png
    - assets/images/ic_checkmark.png
    - assets/images/ic_quran.png
    - assets/images/ic_hijaiyah.png
    - assets/images/ic_sound_wave.png
    - assets/images/img_masjid.png
    - assets/images/ic_point.png
    - assets/images/ic_rank.png
    - assets/images/ic_tuning.png
    - assets/images/bg_wrapped.png
    - assets/images/pressed.png
    - assets/models/best_model.tflite
    - assets/audio/ain.m4a
    - assets/audio/alif.m4a
    - assets/audio/ba.m4a
    - assets/audio/dal.m4a
    - assets/audio/dhad.m4a
    - assets/audio/dzal.m4a
    - assets/audio/fa.m4a
    - assets/audio/ghain.m4a
    - assets/audio/ha.m4a
    - assets/audio/HHa.m4a
    - assets/audio/jim.m4a
    - assets/audio/kaf.m4a
    - assets/audio/kha.m4a
    - assets/audio/lam.m4a
    - assets/audio/mim.m4a
    - assets/audio/nun.m4a
    - assets/audio/qaf.m4a
    - assets/audio/ra.m4a
    - assets/audio/shad.m4a
    - assets/audio/sin.m4a
    - assets/audio/syin.m4a
    - assets/audio/ta.m4a
    - assets/audio/tha.m4a
    - assets/audio/tsa.m4a
    - assets/audio/waw.m4a
    - assets/audio/ya.m4a
    - assets/audio/zai.m4a
    - assets/audio/zha.m4a

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Maqroo
      fonts:
        - asset: assets/fonts/Maqroo-Regular.ttf
