// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh3miz6sfQ58IwShhchpTIkDK474YXemY',
    appId: '1:723399576105:web:4349c5de70ecb9cc51aa38',
    messagingSenderId: '723399576105',
    projectId: 'afdyl-93319',
    authDomain: 'afdyl-93319.firebaseapp.com',
    storageBucket: 'afdyl-93319.firebasestorage.app',
    measurementId: 'G-5RHD5W3PYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMm0SWTnaxfy9ZC-CP147YNyEklNnL6Kk',
    appId: '1:723399576105:android:f453fed535985e7b51aa38',
    messagingSenderId: '723399576105',
    projectId: 'afdyl-93319',
    storageBucket: 'afdyl-93319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPCT16Xm6M_zeokL3gvKJUFY2ZvhgwXb0',
    appId: '1:723399576105:ios:320b5b6adb9ca83d51aa38',
    messagingSenderId: '723399576105',
    projectId: 'afdyl-93319',
    storageBucket: 'afdyl-93319.firebasestorage.app',
    iosBundleId: 'com.example.afdyl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPCT16Xm6M_zeokL3gvKJUFY2ZvhgwXb0',
    appId: '1:723399576105:ios:320b5b6adb9ca83d51aa38',
    messagingSenderId: '723399576105',
    projectId: 'afdyl-93319',
    storageBucket: 'afdyl-93319.firebasestorage.app',
    iosBundleId: 'com.example.afdyl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh3miz6sfQ58IwShhchpTIkDK474YXemY',
    appId: '1:723399576105:web:71de450c7b9d017551aa38',
    messagingSenderId: '723399576105',
    projectId: 'afdyl-93319',
    authDomain: 'afdyl-93319.firebaseapp.com',
    storageBucket: 'afdyl-93319.firebasestorage.app',
    measurementId: 'G-N9TQTKRSVV',
  );

}